# Listen
## 0. Überblick
In diesem Skript geht es darum, den Umgang mit Python und Listen zu üben. Danach solltest du folgendes gelernt haben:
> - Listen in Python erstellen
> - Auf Elemente einer Liste in Python mit index (und index range) zugreifen
> - Über Listen iterieren können (mittels for-Loop)
> - Auf Listen in Listen zugreifen können

## 1. Listen erstellen (und Python basics)

Eine Variable wird in Python mit dem = Zeichen zugewiesen. 

`my_variable = 4`

Jede Variable hat einen **Datentyp**. Dieser Datentyp bestimmt, welche Operationen mit einer Variable gemacht werden können. Hat eine Variable zum Beispiel den Datentyp Integer (Ganzzahl), dann kann diese mit dem /-Zeichen dividiert werden. Bei einer Variable vom Datentyp String (Zeichenkette) geht das nicht.

Python verfügt über eine **dynamische Typisierung**. Das bedeutet, dass Python selbstständig den Datentyp für eine Variable auswählt. Z.B. in Java geht das nicht, dort muss der Datentyp jeweils angegeben werden.

Hier erhält my_variable den Datentyp Integer (Ganzzahl)

`my_variable = 4`

Hier erhält my_variable den Datentyp Float (Fliesskommazahl)

`my_variable = 4.2`

Hier erhält my_variable den Datentyp String. Hierzu werden die "" oder '' Zeichen verwendet um Python mitzuteilen, dass es sich um Text und nicht um zwei Varialben *Hello* und *World* handelt. 
`my_variable = 'Hello World'`

Um **Listen** zu erstellen verwenden wir in Python die eckigen Klammern **[ ]**. Wird ein oder mehrere Elemente (kommagetrennt) in eckigen Klammern geschrieben, dann interpretiert Python diese als Listenelemente. Die einzelnen Elemente der Liste enthalten übrigens dennoch Datentypen welche wiederum dynamisch zugewiesen werden.

`my_list = [1,4,7,8,9]`

>1. Weise in der folgenden Zelle der Variable *list_1* eine Liste mit den Elementen *2, 4, 8, 16, 32, 64* zu.

In [1]:
list_1 = [2, 3, 8, 16, 32, 64]
list_1

[2, 3, 8, 16, 32, 64]

>2. Weise in der folgenden Zelle der Variable *list_2* eine Liste mit den Elementen *Franz, Karl, Weber* zu.

In [3]:
list_2 = ['Franz', 'Karl', 'Weber']
list_2

['Franz', 'Karl', 'Weber']

>3. Erstelle in der folgenden Zelle eine Liste mit Strings und Interger Elementen. Ist das in Python erlaubt?

In [4]:
list_3 = ['Hello', 'World', 42]

list_3

['Hello', 'World', 42]

## 2. Auf Elemente einer Liste zugreifen und Elemente hinzufügen
Wie können wir nun aber auf einzelne Elemente einer Liste zugreifen? Hierzu sind **alle Elemente einer Liste mit einem Index versehen**. Was auf den ersten Blick verwirrend sein kann, ist dass der Index stets bei 0 beginnt. So hat das erste Element den Index 0, das zweite Element den Index 1 usw.

Um nun auf ein Element zuzugreifen werden wiederum die **[ ]**-Klammern verwendet. Der folgende Code erstellt eine Liste und speichert sie in die Variable *some_list*. Danach gibt er das Element am Index 2, also das dritte Element aus.

`
some_list = ['Hallo', 'Welt', '!']
some_list[2]
`

> 1. In der nächsten Zelle wird eine Liste erstellt und ausgegeben. Ändere den Code so ab, dass nur das Wort **spät** aus der Liste ausgegeben wrid.

In [5]:
some_list = ['Wer', 'reitet', 'so', 'spät', 'durch', 'Nacht', 'und', 'Wind']
some_list[3]

'spät'

> 2. Um ein Subset (ein Bereich) einer Liste auszulesen kann der Doppelpunkt (:) verwendet werden. So liest der Befehl `some_list[3:5]` die Elemente zwischen den Indexen 3 (inklusive) und 5 (exklusive) aus. Passe den folgenden Code so an, dass nur die Elemente **['spät', 'durch', 'Nacht']** ausgegeben werden.

In [6]:
some_list[3:6]

['spät', 'durch', 'Nacht']

> 3. Mit dem Index können wir auch Elemente einer Liste ersetzen. Wenn wir z.B. die Listen-Variable *my_list* mit dem Befehl `my_list = [4, 3, 2]` überschreiben können, dann können wir mit dem Befehl `my_list[0] = 5` auch nur ein Element der Listen-Variable ersetzen. In der folgenden Zelle wird eine liste mit Fibonacci-Zahlen erstellt. Allerdings ist ein Element falsch. Ersetze das Element mit der richtigen Zahl. verwende hierfür den `fib[...] = ...` Syntax und ersetze nicht einfach die Zahl in der ersten Zeile.

In [7]:
fib = [1, 1, 2, 3, 5, 8, 14, 21]
#Ersetze hier ein Element

fib[6] = 13

fib

[1, 1, 2, 3, 5, 8, 13, 21]

> 4. Was uns nun noch fehlt ist das Anfügen neuer Elemente. Ein einzelnes Element kann mit dem *.append()*-Befehl einer Liste angehänt werden. möchten wir zum Beispiel der Liste `my_list = [1, 2, 3]` die Zahl *4* anhängen, dann genügt der Befehl `my_list.append(4)`. Alternativ können Listen auch mit dem + Symbol zusammengefügt werden. So könnte die Zahl *4* auch mit dem Befehl `my_list = my_list + [4]` angehänt werden.
Erweitere die Liste *some_list* aus den vorhergehenden Aufgaben, so dass sie nun die Elemente **['Wer', 'reitet', 'so', 'spät', 'durch', 'Nacht', 'und', 'Wind', 'es', 'ist', 'der', 'Vater', 'mit', 'seinem', 'Kind']** enthält. Überlege dir, ob hier der append-Befehl oder die Listenaddition (+ Zeichen) besser ist.

In [11]:
# Möglichkeit 1
some_list = ['Wer', 'reitet', 'so', 'spät', 'durch', 'Nacht', 'und', 'Wind']

some_list = some_list + ['es', 'ist', 'der', 'Vater', 'mit', 'seinem', 'Kind']

print(some_list)

# Möglichkeit 2
some_list = ['Wer', 'reitet', 'so', 'spät', 'durch', 'Nacht', 'und', 'Wind']
for entry in ['es', 'ist', 'der', 'Vater', 'mit', 'seinem', 'Kind']:
    some_list.append(entry)
    
print(some_list)

['Wer', 'reitet', 'so', 'spät', 'durch', 'Nacht', 'und', 'Wind', 'es', 'ist', 'der', 'Vater', 'mit', 'seinem', 'Kind']
['Wer', 'reitet', 'so', 'spät', 'durch', 'Nacht', 'und', 'Wind', 'es', 'ist', 'der', 'Vater', 'mit', 'seinem', 'Kind']

## 3. Über Listen iterieren

Oft wollen wir über eine Liste iterieren (d.h. alle Elemente einer Liste durchgehen) und mit den Listenelementen etwas anstellen. Hierfür benötigen wir Schleifen (for loops). Es gibt zwei Möglichkeiten:

**Mit Index:**

Als erstes können wir einen for-Loop Verwenden um den ganzen Index-Bereich einer Liste durchzugehen. Der Befehl `range(num)` gibt einen sogenannten Iterator zurück. Wir gehen auf das Konzept nicht tiefer ein, es bedeutet aber, dass z.B. `range(4)` ein Objekt ist, welches die Werte 0, 1, 2, 3 durchgeht. `range(5)` würde die Werte 0, 1, 2, 3, 4 druchgehen. Wir kombinieren diesen Befehl mit einem for-Loop. Probiere es aus:

In [5]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

Weiter gibt der Befehl `len(some_list)`  die Länge (Anzahl Elemente) einer Liste zurück. `len(['a', 'b', 'c']` gäbe zum Beispiel 3 zurück. Wir könne range und len mit einem Loop kombinieren, um nun die Indexe einer Liste zu durchschreiten:

In [6]:
my_list = ['a', 'b', 'c', 'd']

for i in range(len(my_list)):
    print(i)

0
1
2
3

Wenn wir nun den Index verwenden um tatsächlich auf die Liste zuzugreifen, kommt folgendes dabei heraus:

In [7]:
my_list = ['a', 'b', 'c', 'd']

for i in range(len(my_list)):
    print(my_list[i])

a
b
c
d

**Ohne Index**

Alternativ können wir mit Loops auch direkt über die Elemente einer Liste iterieren. Der Syntax sieht so aus:

In [8]:
my_list = ['a', 'b', 'c', 'd']

for elem in my_list:
    print(elem)

a
b
c
d

Diese Schreibweise ist um einiges kürzer, dafür kann auf den Index eines Elements aber auch nicht ohne weiteres zugegriffen werden.

> 1. Iteriere über die folgende Liste und schreibe jeweils das Quadrat der Zahl auf die Konsole. Das ergebniss sollte also wie folgt aussehen:
>>
>>1
>>
>>4
>>
>>9
>>
>>16
>>
>>25

In [9]:
my_list = [1, 2, 3, 4, 5]

>2. Nun wollen wir eine neue Liste, basierend auf einer anderen erstellen. Iteriere über die Liste *my_list* und befülle die Liste *second_list* dabei mit den Quadraten der Listenelemente. Das Resultat soll also wiefolgt aussehen: [1, 4, 9, 16, 25]

In [10]:
my_list = [1, 2, 3, 4, 5]
second_list = []

## 4. Listen in Listen

Wenn wir Tabellen darstellen wollen, dann benötigen wir Listen in Listen. Wenn wir zum Beispiel die Tabelle

1  2  3

4  5  6

7  8  9

darstellen wollen, dann entspricht das dem Konstrukt `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`. Wir haben also eine Liste, welche drei weitere Listen enthält. Die Unterlisten entsprechen also den rows (Zeilen). Die Unterlisten enthalten dann wiederum die einzelnen Elemente (in diesem Fall Zahlen). Wenn wir nun auf die Zahl 2 zugreifen möchten, dann müssen wir zuerst die richtige row auswählen (diejenige mit `[1, 2, 3]`) und von dieser dann die Zahl 2. Das resultiert im folgenden Befehl:

`
my_table = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_table[0][1]
`

`my_table[0]` gibt uns die Liste mit Index 0 zurück, also `[1, 2, 3]`. Davon nehmen wir das Element mit index 1, das ist nähmlich die gewünschte Zahl `2`.

> 1. Nun wollen wir zie Zahl 7 erhalten. Passe den folgenden Code so an, dass nicht die ganze Tabelle, sondern nur die Zahl 7 zurückgegeben wird.

In [13]:
my_table = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_table[2][0]

7

> 2. Der folgende Code gibt alle rows der Tabelle aus. Passe den Code so an, dass alle Elemente einzeln zurückgegeben werden. Tipp: Dafür brauchst du eine weitere Schleife in der Schleife.

In [36]:
# Möglichkeit 1
my_table = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for row in my_table:
    for entry in row:
        print(entry)
        
# Möglichkeit 2
for i in range(0,2):
    for j in range(0,3):
        print(my_table[i][j])

#Möglichkeit 2 mit Abhängigkeit von der Länge der Listen
for i in range(0,len(my_table)):
    for j in range(0,len(my_table[i])):
        print(my_table[i][j])

1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9

> 3. Schafst du es auch, die Elemente Spaltenweise auszugeben? Also

>> 1
>>
>> 4
>>
>> 7
>>
>> 2
>>
>> 5
>>
>> ...

In [37]:
my_table = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(0,3):
    for j in range(0,3):
        print(my_table[j][i])

1
4
7
2
5
8
3
6
9

## 5. Übungsaufgaben

**1. Maximum einer Liste**
>
> Die folgende Zelle enthält eine Liste und wir wollen den grössten Wert aus der Liste auslesen (889). Wir gehen aber davon aus, dass die Liste immer wieder zufällig sortiert sein könnte. Du kannst also nicht einfach `my_list[4]` verwenden. Gehe wie folgt vor:
>> a) Erstelle eine Variable `res = 0`
>>
>> b) Iteriere über die Liste
>>
>> c) Überprüfe für jedes Listenelement, ob es grösser ist, als res
>>
>> d) Wenn das Listenelement grösser ist, als res, dann ersetze den Wert von res mit dem Wert des Listenelements.
>>
>> e) Nach der Abschluss der Iteration enthält res den Wert des grössten Listenelements.
>>
>> Falls du den if/else Syntax nicht kennst, wende dich an die Lehrperson

In [24]:
my_list = [8,5,4,467,889,3,3,45,67]

res = 0

for elem in my_list:
    if elem > res:
        res = elem
        
res

889

**2. Index des Maximums einer Liste**
> Die folgende Zelle enthält eine Liste und wir wollen den Index des grössten Werts auslesen (5). Orientiere dich am Vorgehen der vorherigen Aufgabe und passe es wo nötig an.

In [42]:
my_list = [8,5,4,467,889,900,3,45,67]

max_index = 0

for i in range(0, 9):                         # Alternative gine auch range(0, len(my_list))
    if my_list[i] > my_list[max_index]:
        max_index = i
        
print(max_index)

5

**3. Summe einer Liste**
> Die folgende Zelle enthält eine Liste. Iteriere über die Liste und summiere alle Elemente. Das Resultat sollte 45 lauten.

In [43]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

res = 0

for elem in my_list:
    res = res + elem
    
res

45

**4. Rückwärts iterieren 1**
> Die folgende Zelle enthält eine Tabelle. Gib die Werte der Tabelle rückwärts aus. Das Resultat sollte 6, 5, 4, 3, 2,1 lauten.

In [49]:
my_table = [[1, 2], [3, 4], [5, 6]]


for i in range(0,3):
    for j in range(0, 2):
        print(my_table[2-i][1-j])

6
5
4
3
2
1

**4. Rückwärts iterieren 2**
> Die folgende Zelle enthält eine Tabelle. Gib die Werte der Tabelle rückwärts nach Spalten aus. Das Resultat sollte 6, 4, 2, 5, 3, 1 lauten.

In [52]:
my_table = [[1, 2], [3, 4], [5, 6]]

for i in range(0,2):
    for j in range(0,3):
        print(my_table[2-j][1-i])

6
4
2
5
3
1

**6. Tabellen verrechnen**
> Die foglende Zelle enthält zwei Tabellen. Wir wollen eine neue Tabelle erstellen, welche die Elemente mit der selben Position beider Tabellen multipliziert. Das Resultat sollte also `[[10, 18], [14, 32]]` lauten.

In [56]:
table_1 = [[5, 6], [7, 8]]
table_2 = [[2, 3], [2, 4]]
table_3 = []

for i in range(0,2):
    row = []
    for j in range(0,2):
        entry = table_1[i][j] * table_2[i][j]
        row.append(entry)
    table_3.append(row)
    
table_3

[[10, 18], [14, 32]]

## 6. Prüfungsrelevantes Wissen
Für die Prüfung solltest du in der Lage sein:

- Auf Listen-Elemente (auch verschachtelte Listen) zuzugreifen.
- Über Listen mit indexen oder elementweise zu iterieren (for loop)
- Listenelemente mit +, -, \*, / zu verrechnen und mit if/else zu vergleichen
- Neue Listen basierend auf anderen Listen zu erstellen